name: kaleydoskop
description: Uyumsuz gündüz düşlemesi için düş günlüğü uygulaması.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  shared_preferences: ^2.3.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/kaleidoscope.png

flutter:
  uses-material-design: true
  assets:
    - assets/kaleidoscope.png


